import pandas as pd

# Path to the log file generated by the consumer script
log_file_path = "consumer_1mps.log"  # Change this to your actual log file path

# Load the log file into a Pandas DataFrame, specifying the header if needed
data = pd.read_csv(log_file_path)

# Preview the data to ensure it loaded correctly
print("Data Preview:")
print(data.head())

# Sample Analysis

# 1. Calculate the average latency
average_latency = data['Latency'].mean()
print(f"\nAverage Latency: {average_latency:.4f} ms")

# 2. Calculate the median latency
median_latency = data['Latency'].median()
print(f"Median Latency: {median_latency:.4f} ms")

# 3. Count the total number of messages that meet the KPI
kpi_met_count = data[data['KPI'] == 'meets KPI'].shape[0]
print(f"Messages Meeting KPI: {kpi_met_count}")

# 4. Count the total number of messages that do not meet the KPI
kpi_not_met_count = data[data['KPI'] != 'meets KPI'].shape[0]
print(f"Messages Not Meeting KPI: {kpi_not_met_count}")

# 5. Find the top 5 messages with the highest latency
top_5_latency = data.nlargest(5, 'Latency')
print("\nTop 5 Messages with Highest Latency:")
print(top_5_latency)